from __future__ import annotations

import logging

from app.models import GapAnalysisItem, GapAnalysisReport, LLMGapReasoningPayload, QuizResultResponse
from app.services.llm import StructuredLLMClient
from app.utils.prompt_loader import load_prompt

logger = logging.getLogger(__name__)


class KnowledgeGapAnalyzer:
    def __init__(
        self,
        llm_client: StructuredLLMClient,
        target_time_seconds: int = 45,
        llm_enrichment_enabled: bool = False,
    ) -> None:
        self._llm_client = llm_client
        self._target_time_seconds = target_time_seconds
        self._llm_enrichment_enabled = llm_enrichment_enabled

    def _compute_weakness_score(
        self,
        *,
        accuracy: float,
        avg_time: float,
        confidence: float,
        conceptual_errors: int,
        guessing_signals: int,
        confidence_mismatches: int,
        attempts: int,
    ) -> float:
        speed_penalty = max(0.0, min((avg_time / self._target_time_seconds) - 1.0, 1.0))
        error_penalty = conceptual_errors / max(attempts, 1)
        guess_penalty = guessing_signals / max(attempts, 1)
        mismatch_penalty = confidence_mismatches / max(attempts, 1)
        confidence_penalty = max(0.0, 0.55 - confidence)

        score = (
            (1 - accuracy) * 0.45
            + speed_penalty * 0.15
            + error_penalty * 0.2
            + guess_penalty * 0.1
            + mismatch_penalty * 0.05
            + confidence_penalty * 0.05
        )
        return round(max(0.0, min(score, 1.0)), 3)

    async def analyze(self, result: QuizResultResponse) -> GapAnalysisReport:
        rule_candidates: list[GapAnalysisItem] = []
        for idx, perf in enumerate(result.concept_performance, start=1):
            weakness = self._compute_weakness_score(
                accuracy=perf.accuracy,
                avg_time=perf.avg_time,
                confidence=perf.confidence,
                conceptual_errors=perf.conceptual_errors,
                guessing_signals=perf.guessing_signals,
                confidence_mismatches=perf.confidence_mismatches,
                attempts=perf.attempts,
            )
            rule_candidates.append(
                GapAnalysisItem(
                    concept=perf.concept,
                    weakness_score=weakness,
                    misconceptions=["rule_based_signal"] if perf.conceptual_errors > 0 else [],
                    recommendation="Revisit fundamentals and solve targeted practice questions.",
                    priority_rank=idx,
                )
            )

        rule_candidates.sort(key=lambda item: item.weakness_score, reverse=True)
        for rank, item in enumerate(rule_candidates, start=1):
            item.priority_rank = rank

        if self._llm_enrichment_enabled:
            def fallback_reasoning() -> LLMGapReasoningPayload:
                summary = "Rule-based analysis used due to unavailable model reasoning."
                return LLMGapReasoningPayload(weak_concepts=[], summary=summary)

            llm_reasoning = await self._llm_client.invoke_structured(
                system_prompt=load_prompt("diagnoser"),
                user_prompt=(
                    f"User: {result.user_id}\n"
                    f"Topic: {result.topic}\n"
                    f"Overall Accuracy: {result.overall_accuracy}\n"
                    f"Concept performance: {result.concept_performance}\n"
                    "Focus on conceptual issues, confidence mismatch, and weak patterns."
                ),
                output_model=LLMGapReasoningPayload,
                fallback_factory=fallback_reasoning,
                max_retries=0,
            )
        else:
            llm_reasoning = LLMGapReasoningPayload(
                weak_concepts=[],
                summary="Deterministic diagnostics generated by rule-based analyzer.",
            )

        reasoning_map = {item.concept.lower(): item for item in llm_reasoning.weak_concepts}

        enriched: list[GapAnalysisItem] = []
        for item in rule_candidates:
            llm_item = reasoning_map.get(item.concept.lower())
            if llm_item:
                misconceptions = [llm_item.misconception] if llm_item.misconception else item.misconceptions
                recommendation = llm_item.recommendation
            else:
                misconceptions = item.misconceptions or ["needs_reinforcement"]
                recommendation = item.recommendation

            enriched.append(
                GapAnalysisItem(
                    concept=item.concept,
                    weakness_score=item.weakness_score,
                    misconceptions=misconceptions,
                    recommendation=recommendation,
                    priority_rank=item.priority_rank,
                )
            )

        weak_concepts = [item for item in enriched if item.weakness_score >= 0.35] or enriched[: max(1, min(3, len(enriched)))]
        summary = (
            llm_reasoning.summary
            if llm_reasoning.summary
            else "Learner shows specific conceptual gaps requiring prioritized practice."
        )

        logger.info(
            "Gap analysis completed | user_id=%s | weak_concepts=%s",
            result.user_id,
            len(weak_concepts),
        )
        return GapAnalysisReport(
            user_id=result.user_id,
            topic=result.topic,
            weak_concepts=weak_concepts,
            summary=summary,
        )
