from __future__ import annotations

import re
from typing import Iterable

from app.models.schemas import Difficulty, QuizOption, QuizQuestion


def _question(
    question_id: str,
    topic: str,
    difficulty: Difficulty,
    concept_tag: str,
    prompt: str,
    options: Iterable[tuple[str, str]],
    correct_option_id: str,
    explanation: str,
    misconception_map: dict[str, str] | None = None,
) -> QuizQuestion:
    return QuizQuestion(
        question_id=question_id,
        topic=topic,
        difficulty=difficulty,
        concept_tag=concept_tag,
        prompt=prompt,
        options=[QuizOption(option_id=opt_id, text=text) for opt_id, text in options],
        correct_option_id=correct_option_id,
        explanation=explanation,
        misconception_map=misconception_map or {},
        source="seed_bank",
    )


QUESTION_BANK: dict[str, list[QuizQuestion]] = {
    "react and next.js": [
        _question(
            "rn-q-001",
            "react and next.js",
            Difficulty.easy,
            "hooks_rules",
            "Which statement follows the Rules of Hooks in React?",
            [
                ("A", "Call hooks only at the top level of a function component"),
                ("B", "Call hooks inside loops for repeated state"),
                ("C", "Call hooks only in class component methods"),
                ("D", "Call hooks only after async data returns"),
            ],
            "A",
            "Hooks must run in the same order on every render to preserve state correctly.",
            {"B": "rules_of_hooks_violation"},
        ),
        _question(
            "rn-q-002",
            "react and next.js",
            Difficulty.easy,
            "list_keys",
            "Why does React recommend stable keys when rendering lists?",
            [
                ("A", "Keys allow React to map items across renders efficiently"),
                ("B", "Keys are required for CSS styling"),
                ("C", "Keys prevent all re-renders in child components"),
                ("D", "Keys are only for sorting in JavaScript arrays"),
            ],
            "A",
            "Stable keys help React reconcile list item identity during updates and reordering.",
            {"C": "keys_do_not_block_all_rerenders"},
        ),
        _question(
            "rn-q-003",
            "react and next.js",
            Difficulty.medium,
            "usememo",
            "When is useMemo most useful in a React component?",
            [
                ("A", "When you need to memoize an expensive derived value"),
                ("B", "When you want to run side effects after render"),
                ("C", "When you need to mutate refs in layout"),
                ("D", "When you want to define routes in Next.js"),
            ],
            "A",
            "useMemo caches expensive computed values between renders when dependencies are unchanged.",
            {"B": "useeffect_vs_usememo_confusion"},
        ),
        _question(
            "rn-q-004",
            "react and next.js",
            Difficulty.medium,
            "useeffect_dependencies",
            "What is the effect of omitting a required dependency from a useEffect dependency array?",
            [
                ("A", "The effect may read stale values from previous renders"),
                ("B", "React throws a compile-time syntax error"),
                ("C", "The effect automatically runs only once forever"),
                ("D", "The component is forced to unmount and remount"),
            ],
            "A",
            "Missing dependencies can cause stale closures and behavior that drifts from current state.",
            {"C": "dependency_array_behavior_confusion"},
        ),
        _question(
            "rn-q-005",
            "react and next.js",
            Difficulty.medium,
            "next_data_fetching",
            "In Next.js, which approach is used when a page must fetch fresh data on every request?",
            [
                ("A", "Use server-side rendering for request-time fetching"),
                ("B", "Use static generation with no revalidation"),
                ("C", "Use only client-side CSS modules"),
                ("D", "Use image optimization settings"),
            ],
            "A",
            "Request-time rendering is appropriate when data changes frequently per request.",
            {"B": "ssg_vs_ssr_confusion"},
        ),
        _question(
            "rn-q-006",
            "react and next.js",
            Difficulty.medium,
            "server_vs_client_components",
            "What is a primary benefit of using a Server Component in modern Next.js?",
            [
                ("A", "It can reduce client bundle size by running logic on the server"),
                ("B", "It guarantees offline support without service workers"),
                ("C", "It replaces all API routes automatically"),
                ("D", "It allows hooks like useState on the server"),
            ],
            "A",
            "Server Components keep server-only logic out of the browser bundle and improve payload size.",
            {"D": "server_component_hook_confusion"},
        ),
        _question(
            "rn-q-007",
            "react and next.js",
            Difficulty.hard,
            "render_optimization",
            "Which pattern best avoids unnecessary re-renders caused by unstable function props?",
            [
                ("A", "Memoize callbacks passed to memoized children when dependencies are stable"),
                ("B", "Move all state to global scope"),
                ("C", "Use keys on every nested element"),
                ("D", "Force synchronous rendering"),
            ],
            "A",
            "Stable callback references can prevent avoidable child re-renders in memoized trees.",
            {"C": "keys_are_not_render_perf_switch"},
        ),
        _question(
            "rn-q-008",
            "react and next.js",
            Difficulty.hard,
            "hydration",
            "What commonly causes hydration mismatch warnings in a React SSR application?",
            [
                ("A", "Rendering non-deterministic values differently on server and client"),
                ("B", "Using semantic HTML tags"),
                ("C", "Importing static CSS files"),
                ("D", "Using memoized selectors"),
            ],
            "A",
            "Hydration mismatches happen when initial client markup differs from the server-rendered HTML.",
            {"D": "hydration_not_about_selector_memoization"},
        ),
    ],
    "typescript": [
        _question(
            "ts-q-001",
            "typescript",
            Difficulty.easy,
            "any_vs_unknown",
            "What is the key difference between any and unknown in TypeScript?",
            [
                ("A", "unknown requires type narrowing before use, any does not"),
                ("B", "any is stricter than unknown"),
                ("C", "unknown can only store numbers"),
                ("D", "any works only in interfaces"),
            ],
            "A",
            "unknown is safer because you must narrow it before property access or method calls.",
            {"B": "type_safety_confusion"},
        ),
        _question(
            "ts-q-002",
            "typescript",
            Difficulty.easy,
            "union_narrowing",
            "How can you safely access string methods on a value typed as string | number?",
            [
                ("A", "Use a type guard like typeof value === 'string'"),
                ("B", "Cast directly to string without checks"),
                ("C", "Disable strict mode in tsconfig"),
                ("D", "Declare the variable as never"),
            ],
            "A",
            "Type guards narrow union members and allow safe access to member-specific APIs.",
            {"B": "unsafe_type_assertion"},
        ),
        _question(
            "ts-q-003",
            "typescript",
            Difficulty.medium,
            "generics",
            "Why are generics useful for reusable utility functions?",
            [
                ("A", "They preserve type information across inputs and outputs"),
                ("B", "They remove all compile-time checks"),
                ("C", "They force runtime reflection"),
                ("D", "They can only be used with classes"),
            ],
            "A",
            "Generics allow flexible APIs without sacrificing type inference and safety.",
            {"D": "generics_scope_confusion"},
        ),
        _question(
            "ts-q-004",
            "typescript",
            Difficulty.medium,
            "interface_vs_type",
            "Which statement about interface and type alias is accurate?",
            [
                ("A", "Interfaces can be declaration-merged; type aliases cannot"),
                ("B", "Type aliases cannot represent unions"),
                ("C", "Interfaces cannot describe object shapes"),
                ("D", "Both are forbidden in function signatures"),
            ],
            "A",
            "Interface declarations can merge in the same scope, unlike type aliases.",
            {"B": "type_alias_capabilities_confusion"},
        ),
        _question(
            "ts-q-005",
            "typescript",
            Difficulty.medium,
            "readonly",
            "What does readonly on a property enforce?",
            [
                ("A", "The property cannot be reassigned after initialization"),
                ("B", "The property is always deep-frozen recursively"),
                ("C", "The property is removed from emitted JavaScript"),
                ("D", "The property must be private"),
            ],
            "A",
            "readonly prevents reassignment at compile time but is not deep immutability by itself.",
            {"B": "readonly_vs_deep_immutability"},
        ),
        _question(
            "ts-q-006",
            "typescript",
            Difficulty.medium,
            "mapped_types",
            "Which utility type makes all properties of T optional?",
            [
                ("A", "Partial<T>"),
                ("B", "Required<T>"),
                ("C", "Readonly<T>"),
                ("D", "Pick<T, K>"),
            ],
            "A",
            "Partial maps each property key in T to an optional version of that property.",
            {"B": "required_vs_partial_confusion"},
        ),
        _question(
            "ts-q-007",
            "typescript",
            Difficulty.hard,
            "discriminated_unions",
            "What enables exhaustive checking in a discriminated union switch?",
            [
                ("A", "A shared literal discriminator property plus a never fallback"),
                ("B", "Using any for all union members"),
                ("C", "Converting all members to string"),
                ("D", "Turning off noImplicitAny"),
            ],
            "A",
            "A discriminator narrows each branch, and a never check catches unhandled variants.",
            {"B": "exhaustiveness_requires_specific_types"},
        ),
        _question(
            "ts-q-008",
            "typescript",
            Difficulty.hard,
            "conditional_types",
            "What do conditional types primarily provide?",
            [
                ("A", "Type-level branching logic based on assignability"),
                ("B", "Runtime if statements in generated code"),
                ("C", "Automatic database migrations"),
                ("D", "Guaranteed lower bundle size"),
            ],
            "A",
            "Conditional types let you express type transformations using compile-time conditions.",
            {"B": "compile_time_vs_runtime_confusion"},
        ),
    ],
    "node.js": [
        _question(
            "nd-q-001",
            "node.js",
            Difficulty.easy,
            "event_loop",
            "In Node.js, what runs before the next macrotask after current code execution?",
            [
                ("A", "Microtasks such as Promise callbacks"),
                ("B", "Only setTimeout callbacks"),
                ("C", "Only file system callbacks"),
                ("D", "Nothing until process exit"),
            ],
            "A",
            "Promise microtasks run before the event loop continues to the next macrotask phase.",
            {"B": "microtask_vs_macrotask_confusion"},
        ),
        _question(
            "nd-q-002",
            "node.js",
            Difficulty.easy,
            "env_vars",
            "How are environment variables typically accessed in Node.js?",
            [
                ("A", "Through process.env"),
                ("B", "Through window.localStorage"),
                ("C", "Through document.cookie"),
                ("D", "Through import.meta.styles"),
            ],
            "A",
            "Node exposes environment variables through process.env as string values.",
            {"B": "browser_vs_node_api_confusion"},
        ),
        _question(
            "nd-q-003",
            "node.js",
            Difficulty.medium,
            "express_middleware",
            "What is the role of next() in Express middleware?",
            [
                ("A", "Pass control to the next middleware in the chain"),
                ("B", "Restart the server process"),
                ("C", "Compile TypeScript to JavaScript"),
                ("D", "Flush all database connections"),
            ],
            "A",
            "Calling next() hands off request processing to the next matching middleware or route handler.",
            {"D": "middleware_does_not_manage_db_pool"},
        ),
        _question(
            "nd-q-004",
            "node.js",
            Difficulty.medium,
            "async_error_handling",
            "Which pattern is recommended for handling rejected promises in async functions?",
            [
                ("A", "Use try/catch around awaited calls"),
                ("B", "Ignore rejections because Node retries automatically"),
                ("C", "Use only synchronous callbacks"),
                ("D", "Disable unhandled rejection warnings"),
            ],
            "A",
            "try/catch around await keeps asynchronous failures explicit and controllable.",
            {"B": "promise_rejections_are_not_auto_retried"},
        ),
        _question(
            "nd-q-005",
            "node.js",
            Difficulty.medium,
            "streams",
            "Why are streams preferred for large file processing in Node.js?",
            [
                ("A", "They process data incrementally and reduce memory spikes"),
                ("B", "They force files into memory for faster CPU use"),
                ("C", "They only work for text files"),
                ("D", "They remove the need for backpressure handling"),
            ],
            "A",
            "Streams handle chunks over time and avoid loading entire payloads into memory at once.",
            {"D": "backpressure_is_still_important"},
        ),
        _question(
            "nd-q-006",
            "node.js",
            Difficulty.medium,
            "cjs_vs_esm",
            "Which statement best describes CommonJS versus ESM in Node.js?",
            [
                ("A", "CommonJS uses require/module.exports, ESM uses import/export"),
                ("B", "Both use identical syntax and loader behavior"),
                ("C", "ESM cannot run in modern Node.js"),
                ("D", "CommonJS supports only TypeScript files"),
            ],
            "A",
            "Node supports both module systems with different syntax and resolution semantics.",
            {"B": "module_system_differences_confusion"},
        ),
        _question(
            "nd-q-007",
            "node.js",
            Difficulty.hard,
            "cpu_bound_work",
            "What is an effective approach when CPU-bound work blocks the Node.js event loop?",
            [
                ("A", "Offload to worker threads or another service"),
                ("B", "Add more setTimeout calls in the same thread"),
                ("C", "Replace all awaits with callbacks"),
                ("D", "Use synchronous fs APIs for speed"),
            ],
            "A",
            "Worker threads or external services prevent CPU-heavy tasks from blocking request handling.",
            {"D": "sync_io_can_block_event_loop"},
        ),
        _question(
            "nd-q-008",
            "node.js",
            Difficulty.hard,
            "idempotent_api",
            "Why does idempotency matter for retried POST requests in distributed systems?",
            [
                ("A", "It prevents duplicate side effects from repeated submissions"),
                ("B", "It disables network retries at the transport layer"),
                ("C", "It guarantees zero latency"),
                ("D", "It removes the need for unique identifiers"),
            ],
            "A",
            "Idempotency keys let servers deduplicate logically identical retried operations safely.",
            {"D": "identifiers_still_required"},
        ),
    ],
    "python fundamentals": [
        _question(
            "py-q-001",
            "python fundamentals",
            Difficulty.easy,
            "data_types",
            "Which Python type is mutable?",
            [
                ("A", "tuple"),
                ("B", "str"),
                ("C", "list"),
                ("D", "int"),
            ],
            "C",
            "Lists can be modified in place, unlike tuples, strings, and integers.",
            {"A": "tuple_is_immutable"},
        ),
        _question(
            "py-q-002",
            "python fundamentals",
            Difficulty.easy,
            "list_comprehension",
            "What does [x * 2 for x in [1, 2, 3]] evaluate to?",
            [
                ("A", "[2, 4, 6]"),
                ("B", "[1, 2, 3, 1, 2, 3]"),
                ("C", "6"),
                ("D", "[1, 4, 9]"),
            ],
            "A",
            "The expression doubles each element and returns a new list with transformed values.",
            {"D": "square_vs_double_confusion"},
        ),
        _question(
            "py-q-003",
            "python fundamentals",
            Difficulty.medium,
            "dictionary_lookup",
            "What happens when you access a missing key with dict[key]?",
            [
                ("A", "It returns None"),
                ("B", "It raises KeyError"),
                ("C", "It returns an empty string"),
                ("D", "It adds the key automatically"),
            ],
            "B",
            "Direct index access raises KeyError if the key does not exist in the dictionary.",
            {"A": "dict_get_vs_indexing_confusion"},
        ),
        _question(
            "py-q-004",
            "python fundamentals",
            Difficulty.medium,
            "function_scope",
            "Which keyword lets a nested function modify a variable from its enclosing scope?",
            [
                ("A", "global"),
                ("B", "static"),
                ("C", "nonlocal"),
                ("D", "self"),
            ],
            "C",
            "nonlocal binds assignments to the nearest enclosing function scope variable.",
            {"A": "global_vs_nonlocal_confusion"},
        ),
        _question(
            "py-q-005",
            "python fundamentals",
            Difficulty.medium,
            "error_handling",
            "What is the correct structure for handling exceptions in Python?",
            [
                ("A", "try / except / finally"),
                ("B", "catch / rescue / done"),
                ("C", "attempt / fail / always"),
                ("D", "guard / except / finish"),
            ],
            "A",
            "Python uses try-except-finally for structured exception handling and cleanup.",
            {"B": "syntax_from_other_languages"},
        ),
        _question(
            "py-q-006",
            "python fundamentals",
            Difficulty.hard,
            "generators",
            "What is the key benefit of a generator function using yield?",
            [
                ("A", "It returns values lazily without storing the whole sequence in memory"),
                ("B", "It runs faster than all list operations by default"),
                ("C", "It creates mutable tuples"),
                ("D", "It disables iteration protocols"),
            ],
            "A",
            "Generators produce items on demand, improving memory usage for large sequences.",
            {"B": "lazy_evaluation_vs_speed_confusion"},
        ),
        _question(
            "py-q-007",
            "python fundamentals",
            Difficulty.hard,
            "decorators",
            "What does a decorator primarily do in Python?",
            [
                ("A", "Wrap or modify function behavior without changing its internal code"),
                ("B", "Convert Python to C automatically"),
                ("C", "Create SQL indexes for database queries"),
                ("D", "Compile classes into byte arrays"),
            ],
            "A",
            "Decorators are higher-order callables that extend behavior around existing functions.",
            {"D": "decorator_runtime_purpose_confusion"},
        ),
        _question(
            "py-q-008",
            "python fundamentals",
            Difficulty.hard,
            "asyncio_basics",
            "What is required to run an async coroutine function in Python?",
            [
                ("A", "An event loop such as asyncio.run"),
                ("B", "A separate operating system process per coroutine"),
                ("C", "Only a for-loop over the function name"),
                ("D", "No special runtime support"),
            ],
            "A",
            "Coroutines need an event loop to schedule and execute asynchronous operations.",
            {"B": "coroutine_vs_process_confusion"},
        ),
    ],
    "system design": [
        _question(
            "sd-q-001",
            "system design",
            Difficulty.easy,
            "horizontal_scaling",
            "What is a primary advantage of horizontal scaling over vertical scaling?",
            [
                ("A", "It can increase capacity by adding more nodes incrementally"),
                ("B", "It removes all network complexity"),
                ("C", "It guarantees zero downtime forever"),
                ("D", "It eliminates the need for load balancing"),
            ],
            "A",
            "Horizontal scaling distributes load across nodes and supports gradual capacity growth.",
            {"D": "load_balancing_still_needed"},
        ),
        _question(
            "sd-q-002",
            "system design",
            Difficulty.easy,
            "caching",
            "Why is caching commonly added in front of read-heavy services?",
            [
                ("A", "To reduce latency and offload repeated reads from the primary store"),
                ("B", "To guarantee perfectly fresh data at all times"),
                ("C", "To replace persistence entirely"),
                ("D", "To avoid network calls between services"),
            ],
            "A",
            "Caching improves response time and decreases backend pressure for hot data paths.",
            {"B": "cache_staleness_tradeoff_ignored"},
        ),
        _question(
            "sd-q-003",
            "system design",
            Difficulty.medium,
            "idempotency",
            "What is the main purpose of an idempotency key in API design?",
            [
                ("A", "Prevent duplicate effects when clients retry the same request"),
                ("B", "Encrypt all payload fields"),
                ("C", "Reduce payload size for mobile clients"),
                ("D", "Guarantee causal consistency"),
            ],
            "A",
            "Idempotency keys help servers detect and deduplicate retried operations safely.",
            {"D": "consistency_model_vs_idempotency_confusion"},
        ),
        _question(
            "sd-q-004",
            "system design",
            Difficulty.medium,
            "database_indexing",
            "What is a common tradeoff when adding more database indexes?",
            [
                ("A", "Faster reads but slower writes and increased storage"),
                ("B", "Faster writes and smaller storage"),
                ("C", "Eliminates need for query optimization"),
                ("D", "Guarantees partition tolerance"),
            ],
            "A",
            "Indexes accelerate read paths but add maintenance overhead during inserts and updates.",
            {"C": "indexes_not_substitute_for_query_design"},
        ),
        _question(
            "sd-q-005",
            "system design",
            Difficulty.medium,
            "sharding",
            "Why is choosing a good shard key important?",
            [
                ("A", "It helps distribute load evenly and avoids hot partitions"),
                ("B", "It removes all need for replication"),
                ("C", "It guarantees strict serializable transactions"),
                ("D", "It prevents schema evolution"),
            ],
            "A",
            "Balanced shard keys improve throughput and reduce hotspots under skewed traffic.",
            {"C": "sharding_not_equal_serializability"},
        ),
        _question(
            "sd-q-006",
            "system design",
            Difficulty.hard,
            "eventual_consistency",
            "What does eventual consistency imply in distributed data stores?",
            [
                ("A", "Replicas may temporarily diverge but converge given no new writes"),
                ("B", "All reads are strongly consistent immediately"),
                ("C", "Writes are always rejected during partitions"),
                ("D", "Replication is unnecessary"),
            ],
            "A",
            "Eventual consistency allows temporary divergence while replicas synchronize over time.",
            {"B": "strong_vs_eventual_consistency_confusion"},
        ),
        _question(
            "sd-q-007",
            "system design",
            Difficulty.hard,
            "rate_limiting",
            "Which algorithm is commonly used for smoothing bursty traffic in rate limiting?",
            [
                ("A", "Token bucket"),
                ("B", "Bubble sort"),
                ("C", "Binary search tree"),
                ("D", "Round-robin DNS"),
            ],
            "A",
            "Token bucket allows controlled bursts while enforcing long-term request limits.",
            {"D": "routing_vs_rate_limit_confusion"},
        ),
        _question(
            "sd-q-008",
            "system design",
            Difficulty.hard,
            "observability",
            "What combination best supports production incident diagnosis?",
            [
                ("A", "Metrics, logs, and traces with correlated identifiers"),
                ("B", "Only periodic screenshots"),
                ("C", "Only code comments"),
                ("D", "Only unit test output"),
            ],
            "A",
            "Correlated telemetry enables fast root-cause analysis across distributed components.",
            {"D": "testing_output_not_runtime_observability"},
        ),
    ],
    "data structures": [
        _question(
            "ds-q-001",
            "data structures",
            Difficulty.easy,
            "hash_table",
            "Average-case lookup time in a well-distributed hash table is typically:",
            [
                ("A", "O(1)"),
                ("B", "O(log n)"),
                ("C", "O(n log n)"),
                ("D", "O(n^2)"),
            ],
            "A",
            "Hash tables provide near-constant-time average lookups with good hashing.",
            {"B": "tree_lookup_vs_hash_lookup_confusion"},
        ),
        _question(
            "ds-q-002",
            "data structures",
            Difficulty.easy,
            "stack_queue",
            "Which data structure follows FIFO ordering?",
            [
                ("A", "Queue"),
                ("B", "Stack"),
                ("C", "Heap"),
                ("D", "Binary search tree"),
            ],
            "A",
            "FIFO behavior means the earliest inserted item is removed first.",
            {"B": "lifo_vs_fifo_confusion"},
        ),
        _question(
            "ds-q-003",
            "data structures",
            Difficulty.medium,
            "binary_search",
            "What prerequisite is required for classic binary search on an array?",
            [
                ("A", "The array must be sorted by the search key"),
                ("B", "The array must contain unique values only"),
                ("C", "The array must be implemented as a linked list"),
                ("D", "The array must have even length"),
            ],
            "A",
            "Binary search relies on order to discard half of the remaining search space each step.",
            {"B": "uniqueness_not_required"},
        ),
        _question(
            "ds-q-004",
            "data structures",
            Difficulty.medium,
            "heap_property",
            "In a max-heap, what must be true for every parent node?",
            [
                ("A", "Parent value is greater than or equal to each child"),
                ("B", "Parent value is always the median of subtree"),
                ("C", "Children are sorted in ascending order"),
                ("D", "Tree is perfectly balanced and complete at all levels"),
            ],
            "A",
            "The max-heap invariant enforces parent priority over descendants for efficient extraction.",
            {"C": "heap_is_not_sorted_array"},
        ),
        _question(
            "ds-q-005",
            "data structures",
            Difficulty.medium,
            "graph_traversal",
            "Which traversal naturally finds shortest path by edge count in an unweighted graph?",
            [
                ("A", "Breadth-first search"),
                ("B", "Depth-first search"),
                ("C", "Topological sort"),
                ("D", "In-order traversal"),
            ],
            "A",
            "BFS explores level by level, yielding minimum hop paths in unweighted graphs.",
            {"B": "dfs_not_minimum_hops"},
        ),
        _question(
            "ds-q-006",
            "data structures",
            Difficulty.hard,
            "trie",
            "What is a common strength of a trie compared to a hash map for strings?",
            [
                ("A", "Efficient prefix queries"),
                ("B", "Lower memory use in every case"),
                ("C", "Guaranteed O(1) insertion by hash"),
                ("D", "Native support for weighted shortest path"),
            ],
            "A",
            "Tries are optimized for prefix-based operations like autocomplete and dictionary lookups.",
            {"B": "trie_memory_tradeoff_ignored"},
        ),
        _question(
            "ds-q-007",
            "data structures",
            Difficulty.hard,
            "balanced_trees",
            "Why do self-balancing BSTs (like AVL/Red-Black) rebalance after updates?",
            [
                ("A", "To keep operations near O(log n) by limiting tree height"),
                ("B", "To convert all nodes into arrays"),
                ("C", "To remove duplicate keys automatically"),
                ("D", "To avoid recursion entirely"),
            ],
            "A",
            "Balancing prevents degeneration into linear chains that hurt search and update performance.",
            {"C": "balancing_not_duplicate_removal"},
        ),
        _question(
            "ds-q-008",
            "data structures",
            Difficulty.hard,
            "amortized_analysis",
            "Amortized analysis of dynamic array append typically yields:",
            [
                ("A", "O(1) average over a sequence of operations"),
                ("B", "O(n) for every single append"),
                ("C", "O(log n) only if array is sorted"),
                ("D", "O(n^2) due to contiguous memory"),
            ],
            "A",
            "Occasional resize costs are spread over many cheap appends in amortized analysis.",
            {"B": "worst_case_vs_amortized_confusion"},
        ),
    ],
    "sql": [
        _question(
            "sq-q-001",
            "sql",
            Difficulty.easy,
            "where_vs_having",
            "What is the key difference between WHERE and HAVING?",
            [
                ("A", "WHERE filters rows before grouping, HAVING filters groups after aggregation"),
                ("B", "HAVING is used only for sorting"),
                ("C", "WHERE can only be used with COUNT"),
                ("D", "They are fully interchangeable in all queries"),
            ],
            "A",
            "WHERE applies to raw rows, while HAVING applies after GROUP BY aggregations.",
            {"D": "query_stage_confusion"},
        ),
        _question(
            "sq-q-002",
            "sql",
            Difficulty.easy,
            "join_type",
            "Which join returns all matching rows from both tables and unmatched rows with NULLs?",
            [
                ("A", "FULL OUTER JOIN"),
                ("B", "INNER JOIN"),
                ("C", "CROSS JOIN"),
                ("D", "SELF JOIN"),
            ],
            "A",
            "A full outer join keeps all rows from both sides and fills missing matches with NULLs.",
            {"B": "inner_join_drops_unmatched_rows"},
        ),
        _question(
            "sq-q-003",
            "sql",
            Difficulty.medium,
            "index_usage",
            "Why can a B-tree index improve query performance?",
            [
                ("A", "It helps avoid scanning the entire table for selective predicates"),
                ("B", "It encrypts rows at rest automatically"),
                ("C", "It removes the need for transactions"),
                ("D", "It guarantees perfect cardinality estimates"),
            ],
            "A",
            "Indexes speed lookups by narrowing searched rows before fetching full records.",
            {"D": "estimates_depend_on_stats"},
        ),
        _question(
            "sq-q-004",
            "sql",
            Difficulty.medium,
            "group_by",
            "Which query element is required when selecting non-aggregated columns with aggregates?",
            [
                ("A", "GROUP BY for the non-aggregated selected columns"),
                ("B", "ORDER BY only"),
                ("C", "LIMIT only"),
                ("D", "UNION ALL only"),
            ],
            "A",
            "Grouping defines how rows are partitioned before aggregate functions are computed.",
            {"B": "ordering_is_not_grouping"},
        ),
        _question(
            "sq-q-005",
            "sql",
            Difficulty.medium,
            "acid",
            "In ACID properties, what does Atomicity ensure?",
            [
                ("A", "A transaction fully succeeds or fully rolls back"),
                ("B", "Transactions are always globally ordered across regions"),
                ("C", "All reads are lock-free"),
                ("D", "Indexes never become fragmented"),
            ],
            "A",
            "Atomicity guarantees all-or-nothing behavior for operations within a transaction.",
            {"B": "distributed_ordering_not_atomicity"},
        ),
        _question(
            "sq-q-006",
            "sql",
            Difficulty.hard,
            "window_functions",
            "What is a typical use case for SQL window functions?",
            [
                ("A", "Compute rankings or running totals without collapsing result rows"),
                ("B", "Replace primary keys"),
                ("C", "Drop duplicate tables"),
                ("D", "Change transaction isolation globally"),
            ],
            "A",
            "Window functions operate over row windows while preserving row-level detail.",
            {"C": "window_functions_not_ddl"},
        ),
        _question(
            "sq-q-007",
            "sql",
            Difficulty.hard,
            "normalization",
            "What problem does normalization primarily address?",
            [
                ("A", "Data redundancy and update anomalies"),
                ("B", "Query syntax highlighting"),
                ("C", "Network packet loss"),
                ("D", "Automatic sharding"),
            ],
            "A",
            "Normalization organizes schema to reduce duplication and inconsistent update behavior.",
            {"D": "normalization_not_sharding"},
        ),
        _question(
            "sq-q-008",
            "sql",
            Difficulty.hard,
            "isolation_levels",
            "Which anomaly can SERIALIZABLE isolation prevent compared to weaker levels?",
            [
                ("A", "Phantom reads caused by concurrent inserts or updates"),
                ("B", "Incorrect SQL syntax"),
                ("C", "Missing indexes"),
                ("D", "Expired passwords"),
            ],
            "A",
            "Serializable isolation enforces strict transaction ordering to prevent phantom anomalies.",
            {"C": "isolation_not_indexing"},
        ),
    ],
    "software engineering fundamentals": [
        _question(
            "se-q-001",
            "software engineering fundamentals",
            Difficulty.easy,
            "version_control",
            "What is a key benefit of using feature branches in Git workflows?",
            [
                ("A", "They isolate changes for review before merging"),
                ("B", "They permanently replace the main branch"),
                ("C", "They disable commit history"),
                ("D", "They avoid merge conflicts completely"),
            ],
            "A",
            "Feature branches keep work isolated and make code review and rollback safer.",
            {"D": "conflicts_can_still_happen"},
        ),
        _question(
            "se-q-002",
            "software engineering fundamentals",
            Difficulty.medium,
            "testing_pyramid",
            "In the testing pyramid, which layer should generally be most numerous?",
            [
                ("A", "Unit tests"),
                ("B", "End-to-end tests"),
                ("C", "Manual smoke tests"),
                ("D", "Load tests"),
            ],
            "A",
            "Unit tests are fast and focused, so they usually form the broad base of coverage.",
            {"B": "e2e_tests_are_slower_and_costlier"},
        ),
        _question(
            "se-q-003",
            "software engineering fundamentals",
            Difficulty.medium,
            "code_review",
            "What is the primary goal of a good code review?",
            [
                ("A", "Improve correctness, maintainability, and shared understanding"),
                ("B", "Maximize line-by-line criticism"),
                ("C", "Avoid any discussion about architecture"),
                ("D", "Approve all changes immediately to increase throughput"),
            ],
            "A",
            "Effective reviews reduce defects and improve team alignment on design and quality.",
            {"B": "review_should_be_constructive"},
        ),
        _question(
            "se-q-004",
            "software engineering fundamentals",
            Difficulty.hard,
            "observability",
            "Why are structured logs preferred over unstructured text logs at scale?",
            [
                ("A", "They are queryable and easier to correlate across systems"),
                ("B", "They eliminate all need for metrics"),
                ("C", "They avoid application instrumentation"),
                ("D", "They guarantee no log volume growth"),
            ],
            "A",
            "Structured logs support reliable filtering, aggregation, and cross-service diagnostics.",
            {"B": "observability_needs_multiple_signals"},
        ),
    ],
    "machine learning": [
        _question(
            "ml-q-001",
            "machine learning",
            Difficulty.easy,
            "train_test_split",
            "What is the main purpose of a test set in supervised learning?",
            [
                ("A", "Tune hyperparameters"),
                ("B", "Measure model generalization"),
                ("C", "Increase training data size"),
                ("D", "Remove outliers"),
            ],
            "B",
            "Test data estimates model performance on unseen examples.",
            {"A": "validation_vs_test_confusion"},
        ),
        _question(
            "ml-q-002",
            "machine learning",
            Difficulty.easy,
            "bias_variance",
            "High variance in a model usually indicates:",
            [
                ("A", "Underfitting"),
                ("B", "Overfitting"),
                ("C", "Data leakage"),
                ("D", "Low dimensionality"),
            ],
            "B",
            "High variance means the model memorizes training data and generalizes poorly.",
            {"A": "bias_vs_variance_confusion"},
        ),
        _question(
            "ml-q-003",
            "machine learning",
            Difficulty.medium,
            "cross_validation",
            "Why is k-fold cross-validation useful?",
            [
                ("A", "It estimates model performance more robustly across splits"),
                ("B", "It guarantees perfect production accuracy"),
                ("C", "It removes feature engineering"),
                ("D", "It replaces all holdout testing"),
            ],
            "A",
            "Cross-validation reduces dependence on a single split and gives more stable estimates.",
            {"D": "cv_and_holdout_can_coexist"},
        ),
        _question(
            "ml-q-004",
            "machine learning",
            Difficulty.medium,
            "regularization",
            "What is a common effect of stronger regularization?",
            [
                ("A", "Reduced overfitting risk"),
                ("B", "Higher variance always"),
                ("C", "Guaranteed lower bias"),
                ("D", "No change in model complexity"),
            ],
            "A",
            "Regularization constrains model complexity, often reducing overfitting on training data.",
            {"C": "bias_variance_tradeoff_ignored"},
        ),
    ],
}


TOPIC_ALIASES: dict[str, tuple[str, ...]] = {
    "react and next.js": ("react", "next", "next.js", "react.js", "frontend react"),
    "typescript": ("typescript", "type script", "ts", "ts basics"),
    "node.js": ("node", "nodejs", "node.js", "express", "backend node"),
    "python fundamentals": ("python", "python basics", "python fundamentals", "py", "django", "fastapi"),
    "system design": ("system design", "distributed systems", "scalability", "architecture"),
    "data structures": ("data structures", "dsa", "algorithms", "algorithm"),
    "sql": ("sql", "database", "postgres", "mysql", "query language"),
    "software engineering fundamentals": ("software engineering", "software engineer", "engineering fundamentals"),
    "machine learning": ("machine learning", "ml", "modeling"),
}


def _normalize(topic: str) -> str:
    cleaned = re.sub(r"[^a-z0-9+.# ]+", " ", topic.strip().lower())
    return re.sub(r"\s+", " ", cleaned).strip()


def _resolve_topic_key(topic: str) -> str | None:
    normalized = _normalize(topic)
    if not normalized:
        return None
    if normalized in QUESTION_BANK:
        return normalized

    for canonical, aliases in TOPIC_ALIASES.items():
        if normalized == canonical or normalized in aliases:
            return canonical
        if any(alias in normalized or normalized in alias for alias in aliases):
            return canonical

    return None


def get_seed_questions(topic: str) -> list[QuizQuestion]:
    key = _resolve_topic_key(topic)
    if key and key in QUESTION_BANK:
        return [question.model_copy(deep=True) for question in QUESTION_BANK[key]]

    fallback_pool = (
        QUESTION_BANK["software engineering fundamentals"]
        + QUESTION_BANK["python fundamentals"]
        + QUESTION_BANK["machine learning"]
    )
    return [question.model_copy(deep=True) for question in fallback_pool]

