from app.models import Difficulty, QuizOption, QuizQuestion


QUESTION_BANK: dict[str, list[QuizQuestion]] = {
    "python fundamentals": [
        QuizQuestion(
            question_id="py-q-001",
            topic="python fundamentals",
            difficulty=Difficulty.easy,
            concept_tag="data_types",
            prompt="Which Python data type is immutable?",
            options=[
                QuizOption(option_id="A", text="list"),
                QuizOption(option_id="B", text="dict"),
                QuizOption(option_id="C", text="set"),
                QuizOption(option_id="D", text="tuple"),
            ],
            correct_option_id="D",
            explanation="Tuples are immutable after creation.",
            misconception_map={"A": "mutability_confusion", "B": "mapping_vs_sequence"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="py-q-002",
            topic="python fundamentals",
            difficulty=Difficulty.medium,
            concept_tag="list_comprehension",
            prompt="What does `[x * 2 for x in range(3)]` evaluate to?",
            options=[
                QuizOption(option_id="A", text="[0, 1, 2]"),
                QuizOption(option_id="B", text="[0, 2, 4]"),
                QuizOption(option_id="C", text="[2, 4, 6]"),
                QuizOption(option_id="D", text="[1, 2, 3]"),
            ],
            correct_option_id="B",
            explanation="The expression multiplies each value in `range(3)` by 2.",
            misconception_map={"A": "transformation_ignored", "C": "range_start_confusion"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="py-q-003",
            topic="python fundamentals",
            difficulty=Difficulty.hard,
            concept_tag="asyncio_basics",
            prompt="Why is `await` required before an async function call inside another async function?",
            options=[
                QuizOption(option_id="A", text="It converts a function into a coroutine."),
                QuizOption(option_id="B", text="It waits for coroutine completion without blocking event loop."),
                QuizOption(option_id="C", text="It automatically catches exceptions."),
                QuizOption(option_id="D", text="It forces multithreading execution."),
            ],
            correct_option_id="B",
            explanation="`await` suspends the current coroutine until awaited coroutine completes.",
            misconception_map={"A": "coroutine_definition_confusion", "D": "async_vs_threading"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="py-q-004",
            topic="python fundamentals",
            difficulty=Difficulty.easy,
            concept_tag="control_flow",
            prompt="Which keyword is used to exit a loop immediately in Python?",
            options=[
                QuizOption(option_id="A", text="continue"),
                QuizOption(option_id="B", text="break"),
                QuizOption(option_id="C", text="return"),
                QuizOption(option_id="D", text="pass"),
            ],
            correct_option_id="B",
            explanation="`break` exits the loop immediately.",
            misconception_map={"A": "continue_vs_break", "C": "function_vs_loop_scope"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="py-q-005",
            topic="python fundamentals",
            difficulty=Difficulty.medium,
            concept_tag="function_scope",
            prompt="What happens when a variable is assigned inside a function without `global`?",
            options=[
                QuizOption(option_id="A", text="It updates the global variable automatically."),
                QuizOption(option_id="B", text="It creates or updates a local variable in that function."),
                QuizOption(option_id="C", text="It raises an exception by default."),
                QuizOption(option_id="D", text="It becomes immutable."),
            ],
            correct_option_id="B",
            explanation="Assignments inside a function are local unless declared `global` or `nonlocal`.",
            misconception_map={"A": "scope_leakage_confusion", "C": "assignment_semantics_confusion"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="py-q-006",
            topic="python fundamentals",
            difficulty=Difficulty.hard,
            concept_tag="error_handling",
            prompt="What is the purpose of the `finally` block in Python exception handling?",
            options=[
                QuizOption(option_id="A", text="It runs only if an exception occurs."),
                QuizOption(option_id="B", text="It runs only if no exception occurs."),
                QuizOption(option_id="C", text="It always runs, typically for cleanup."),
                QuizOption(option_id="D", text="It suppresses all exceptions automatically."),
            ],
            correct_option_id="C",
            explanation="`finally` executes regardless of exception outcome, useful for resource cleanup.",
            misconception_map={"A": "except_vs_finally_confusion", "D": "exception_suppression_confusion"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="py-q-007",
            topic="python fundamentals",
            difficulty=Difficulty.easy,
            concept_tag="collections",
            prompt="Which collection type stores unique values only?",
            options=[
                QuizOption(option_id="A", text="list"),
                QuizOption(option_id="B", text="tuple"),
                QuizOption(option_id="C", text="set"),
                QuizOption(option_id="D", text="dict"),
            ],
            correct_option_id="C",
            explanation="A set enforces uniqueness of elements.",
            misconception_map={"D": "dictionary_key_value_confusion"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="py-q-008",
            topic="python fundamentals",
            difficulty=Difficulty.medium,
            concept_tag="string_methods",
            prompt="What is returned by `'python'.upper()`?",
            options=[
                QuizOption(option_id="A", text="'PYTHON'"),
                QuizOption(option_id="B", text="'Python'"),
                QuizOption(option_id="C", text="'python'"),
                QuizOption(option_id="D", text="An error, strings are immutable."),
            ],
            correct_option_id="A",
            explanation="`upper()` returns a new uppercase string.",
            misconception_map={"D": "immutability_method_confusion"},
            source="seed_bank",
        ),
    ],
    "machine learning": [
        QuizQuestion(
            question_id="ml-q-001",
            topic="machine learning",
            difficulty=Difficulty.easy,
            concept_tag="train_test_split",
            prompt="What is the main purpose of a test set in supervised learning?",
            options=[
                QuizOption(option_id="A", text="Tune hyperparameters"),
                QuizOption(option_id="B", text="Measure model generalization"),
                QuizOption(option_id="C", text="Increase training data size"),
                QuizOption(option_id="D", text="Remove outliers"),
            ],
            correct_option_id="B",
            explanation="Test data estimates performance on unseen examples.",
            misconception_map={"A": "validation_vs_test_confusion"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="ml-q-002",
            topic="machine learning",
            difficulty=Difficulty.medium,
            concept_tag="bias_variance",
            prompt="High variance in a model usually indicates:",
            options=[
                QuizOption(option_id="A", text="Underfitting"),
                QuizOption(option_id="B", text="Overfitting"),
                QuizOption(option_id="C", text="Data leakage"),
                QuizOption(option_id="D", text="Low model complexity"),
            ],
            correct_option_id="B",
            explanation="High variance means model is too sensitive to training data noise.",
            misconception_map={"A": "bias_variance_confusion", "D": "complexity_inversion"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="ml-q-003",
            topic="machine learning",
            difficulty=Difficulty.hard,
            concept_tag="gradient_descent",
            prompt="What does the learning rate in gradient descent primarily control?",
            options=[
                QuizOption(option_id="A", text="Model depth"),
                QuizOption(option_id="B", text="Batch size"),
                QuizOption(option_id="C", text="Step size of parameter updates"),
                QuizOption(option_id="D", text="Loss function type"),
            ],
            correct_option_id="C",
            explanation="Learning rate determines how large each optimization step is.",
            misconception_map={"B": "optimization_hyperparam_confusion"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="ml-q-004",
            topic="machine learning",
            difficulty=Difficulty.easy,
            concept_tag="classification_metrics",
            prompt="Which metric is most directly computed from true positives and false positives?",
            options=[
                QuizOption(option_id="A", text="Recall"),
                QuizOption(option_id="B", text="Precision"),
                QuizOption(option_id="C", text="Specificity"),
                QuizOption(option_id="D", text="MAE"),
            ],
            correct_option_id="B",
            explanation="Precision = TP / (TP + FP).",
            misconception_map={"A": "precision_recall_confusion"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="ml-q-005",
            topic="machine learning",
            difficulty=Difficulty.medium,
            concept_tag="feature_scaling",
            prompt="Why is feature scaling often used before gradient-based optimization?",
            options=[
                QuizOption(option_id="A", text="To reduce dataset size."),
                QuizOption(option_id="B", text="To make optimization converge faster and more stably."),
                QuizOption(option_id="C", text="To remove all outliers."),
                QuizOption(option_id="D", text="To increase model variance."),
            ],
            correct_option_id="B",
            explanation="Scaling helps avoid highly uneven gradient steps across features.",
            misconception_map={"C": "scaling_vs_outlier_treatment_confusion"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="ml-q-006",
            topic="machine learning",
            difficulty=Difficulty.hard,
            concept_tag="regularization",
            prompt="What is the main effect of increasing L2 regularization strength?",
            options=[
                QuizOption(option_id="A", text="It increases coefficient magnitudes."),
                QuizOption(option_id="B", text="It penalizes large weights and can reduce overfitting."),
                QuizOption(option_id="C", text="It guarantees zero training error."),
                QuizOption(option_id="D", text="It removes all correlated features."),
            ],
            correct_option_id="B",
            explanation="L2 adds weight penalty to reduce overfitting risk.",
            misconception_map={"A": "regularization_direction_confusion"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="ml-q-007",
            topic="machine learning",
            difficulty=Difficulty.easy,
            concept_tag="model_evaluation",
            prompt="Why use cross-validation during model selection?",
            options=[
                QuizOption(option_id="A", text="To permanently increase training data."),
                QuizOption(option_id="B", text="To estimate generalization across different data splits."),
                QuizOption(option_id="C", text="To avoid preprocessing."),
                QuizOption(option_id="D", text="To replace a test set completely in final reporting."),
            ],
            correct_option_id="B",
            explanation="Cross-validation gives robust validation estimates across folds.",
            misconception_map={"D": "validation_test_purpose_confusion"},
            source="seed_bank",
        ),
        QuizQuestion(
            question_id="ml-q-008",
            topic="machine learning",
            difficulty=Difficulty.medium,
            concept_tag="loss_functions",
            prompt="For binary classification, which loss is commonly used with logistic regression?",
            options=[
                QuizOption(option_id="A", text="Mean squared error only"),
                QuizOption(option_id="B", text="Cross-entropy (log loss)"),
                QuizOption(option_id="C", text="Hinge loss only"),
                QuizOption(option_id="D", text="Huber loss"),
            ],
            correct_option_id="B",
            explanation="Logistic regression is typically optimized with log loss.",
            misconception_map={"A": "regression_vs_classification_loss_confusion"},
            source="seed_bank",
        ),
    ],
}


def get_seed_questions(topic: str) -> list[QuizQuestion]:
    normalized = topic.strip().lower()
    if normalized in QUESTION_BANK:
        return [q.model_copy(deep=True) for q in QUESTION_BANK[normalized]]
    fallback_pool = QUESTION_BANK["python fundamentals"] + QUESTION_BANK["machine learning"]
    return [q.model_copy(deep=True) for q in fallback_pool]

