import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Calendar, Download, TrendingUp, Clock, BarChart2, Target } from 'lucide-react'
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis
} from 'recharts'
import useStore from '../../store/useStore'
import { Avatar } from '../../components/ui/index'
import { luminaApi } from '../../api/luminaApi'
import { mapProgressToStore, mapResourcesToStore } from '../../api/mappers'
import { downloadLearningReportPdf } from '../../lib/pdfReport'

const toPercent = (value) => {
  const numeric = Number(value || 0)
  if (!Number.isFinite(numeric)) return 0
  return Math.round(numeric <= 1 ? numeric * 100 : numeric)
}

const getMostRecentReport = (reportHistory) =>
  [...(Array.isArray(reportHistory) ? reportHistory : [])].sort(
    (left, right) => new Date(right.createdAt).getTime() - new Date(left.createdAt).getTime()
  )[0] || null

const isPlaceholderSummary = (value) => {
  const text = String(value || '').trim()
  if (!text) return true
  return [
    /deterministic diagnostics generated by rule-based analyzer/i,
    /rule-based analysis used due to unavailable model reasoning/i,
    /^no summary available\.?$/i,
  ].some((pattern) => pattern.test(text))
}

const buildDynamicSummary = ({ entry, progress, latestQuiz }) => {
  const topic = entry?.topic || entry?.raw?.plan?.topic || latestQuiz?.result?.topic || 'Learning Track'
  const accuracyValue =
    typeof entry?.accuracy === 'number'
      ? entry.accuracy
      : typeof latestQuiz?.result?.overall_accuracy !== 'undefined'
        ? toPercent(latestQuiz.result.overall_accuracy)
        : progress?.quizAverage

  const weakConcepts = Array.isArray(entry?.weakConcepts)
    ? entry.weakConcepts
    : Array.isArray(entry?.raw?.gap_report?.weak_concepts)
      ? entry.raw.gap_report.weak_concepts.map((item) => ({
          concept: item.concept,
          weaknessScore: Number(item.weakness_score || 0),
        }))
      : []

  const topWeak = weakConcepts
    .slice()
    .sort((left, right) => Number(right.weaknessScore || 0) - Number(left.weaknessScore || 0))
    .slice(0, 2)
    .map((item) => `${item.concept} (${Math.round(Number(item.weaknessScore || 0) * 100)}%)`)
    .join(', ')

  const weekCount =
    Number(entry?.planWeeks || 0) ||
    (Array.isArray(entry?.raw?.plan?.weeks) ? entry.raw.plan.weeks.length : 0)

  const goalProgress = `${progress?.weeklyGoals?.completed || 0}/${progress?.weeklyGoals?.total || 0}`
  const accuracyText = typeof accuracyValue === 'number' && Number.isFinite(accuracyValue) ? `${Math.round(accuracyValue)}%` : 'N/A'

  return `Current ${topic} performance is ${accuracyText} accuracy with weekly goal progress ${goalProgress}. ${
    topWeak
      ? `Priority improvement areas are ${topWeak}.`
      : 'Continue quiz check-ins to detect priority weak concepts.'
  } ${weekCount ? `Your generated plan spans ${weekCount} week(s).` : 'Generate a fresh plan to unlock structured weekly actions.'}`
}

const extractWeekTasks = (week) => {
  const fromDailyPlans = []
  ;(Array.isArray(week?.daily_tasks) ? week.daily_tasks : []).forEach((dailyPlan) => {
    const dayLabel = dailyPlan?.day ? `${dailyPlan.day}: ` : ''
    ;(Array.isArray(dailyPlan?.daily_tasks) ? dailyPlan.daily_tasks : []).forEach((task) => {
      if (task?.title) fromDailyPlans.push(`${dayLabel}${task.title}`)
    })
  })

  if (fromDailyPlans.length) return fromDailyPlans

  const fromWeekTasks = []
  ;(Array.isArray(week?.tasks) ? week.tasks : []).forEach((task) => {
    if (task?.title) {
      const dayLabel = task?.day ? `${task.day}: ` : ''
      fromWeekTasks.push(`${dayLabel}${task.title}`)
    }
  })
  return fromWeekTasks
}

const normalizeText = (value) => String(value || '').trim().toLowerCase()

const collectPlanResources = (reportEntry) => {
  const conceptMap = new Map()
  const weeks = Array.isArray(reportEntry?.raw?.plan?.weeks) ? reportEntry.raw.plan.weeks : []
  weeks.forEach((week) => {
    ;(Array.isArray(week?.daily_tasks) ? week.daily_tasks : []).forEach((day) => {
      ;(Array.isArray(day?.daily_tasks) ? day.daily_tasks : []).forEach((task) => {
        const resource = task?.resource
        const concept = normalizeText(task?.concept_tag)
        if (!concept || !resource?.url) return
        const bucket = conceptMap.get(concept) || []
        bucket.push({
          title: resource.title,
          url: resource.url,
          provider: resource.provider || '',
          type: resource.resource_type || '',
        })
        conceptMap.set(concept, bucket)
      })
    })
  })
  return conceptMap
}

const buildWeeklyPathPreview = (reportEntry) => {
  const weeks = Array.isArray(reportEntry?.raw?.plan?.weeks) ? reportEntry.raw.plan.weeks : []
  return weeks.slice(0, 3).map((week, index) => {
    const weekNumber = Number(week?.week || 0) || index + 1
    const tasks = extractWeekTasks(week).slice(0, 3)
    return {
      week: weekNumber,
      goal: week?.goal || `Week ${weekNumber} improvement sprint`,
      tasks,
    }
  })
}

const Toast = ({ msg, onClose }) => (
  <div className="fixed bottom-6 right-6 z-[999] flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium text-white shadow-xl"
    style={{ background: 'rgba(30,41,59,0.95)', border: '1px solid rgba(59,130,246,0.4)', backdropFilter: 'blur(12px)' }}>
    <i className="fa-solid fa-circle-check text-blue-400" />
    {msg}
    <button onClick={onClose} className="ml-2 text-slate-400 hover:text-white"><i className="fa-solid fa-xmark" /></button>
  </div>
)

const ProgressLineTooltip = ({ active, payload, label }) => {
  if (active && payload?.length) {
    return (
      <div className="custom-tooltip">
        <p className="text-slate-400 text-xs mb-1">{label}</p>
        <p className="font-semibold">{payload[0].value}%</p>
      </div>
    )
  }
  return null
}

const ProgressPage = () => {
  const user = useStore(s => s.user)
  const progress = useStore(s => s.progress)
  const setProgress = useStore(s => s.setProgress)
  const latestQuiz = useStore(s => s.latestQuiz)
  const resources = useStore(s => s.resources)
  const setResources = useStore(s => s.setResources)
  const reportHistory = useStore(s => s.reportHistory)
  const addReportHistory = useStore(s => s.addReportHistory)
  const [moduleFilter, setModuleFilter] = useState('All Modules')
  const [dateRange, setDateRange] = useState('Last 30 Days')
  const [note, setNote] = useState('')
  const [notes, setNotes] = useState([])
  const [toast, setToast] = useState(null)

  const showToast = (msg) => { setToast(msg); setTimeout(() => setToast(null), 2500) }

  useEffect(() => {
    const loadProgress = async () => {
      if (!user?.id || !user?.isAuthenticated) return
      if (!String(user.id).startsWith('user_')) return
      try {
        const summary = await luminaApi.getProgress(user.id)
        setProgress(mapProgressToStore(summary))
      } catch (apiError) {
        showToast(apiError?.message || 'Using local progress snapshot.')
      }

      try {
        const report = await luminaApi.getPlanReport(user.id)
        if (report?.plan || report?.gap_report || report?.validation) {
          addReportHistory({
            id: `${user.id}_${report?.gap_report?.generated_at || 'latest'}`,
            createdAt: report?.gap_report?.generated_at || new Date().toISOString(),
            source: 'backend',
            topic: report?.plan?.topic || 'Learning Plan',
            summary: report?.gap_report?.summary || '',
            weakConcepts: Array.isArray(report?.gap_report?.weak_concepts)
              ? report.gap_report.weak_concepts.map((item) => ({
                  concept: item.concept,
                  weaknessScore: Number(item.weakness_score || 0),
                  recommendation: item.recommendation || '',
                  misconceptions: Array.isArray(item.misconceptions) ? item.misconceptions : [],
                }))
              : [],
            validationIssues: Array.isArray(report?.validation?.issues) ? report.validation.issues : [],
            planWeeks: Array.isArray(report?.plan?.weeks) ? report.plan.weeks.length : 0,
            raw: report,
          })
        }
      } catch {
        // Ignore missing report history endpoint or 404 responses.
      }
    }

    loadProgress()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user?.id, user?.isAuthenticated])

  const handleExport = async () => {
    try {
      let latestReport = getMostRecentReport(reportHistory)

      if (!latestReport && user?.id && user?.isAuthenticated && String(user.id).startsWith('user_')) {
        try {
          const report = await luminaApi.getPlanReport(user.id)
          if (report?.plan || report?.gap_report || report?.validation) {
            latestReport = {
              id: `${user.id}_${report?.gap_report?.generated_at || 'latest'}`,
              createdAt: report?.gap_report?.generated_at || new Date().toISOString(),
              source: 'backend',
              topic: report?.plan?.topic || 'Learning Plan',
              summary: report?.gap_report?.summary || '',
              weakConcepts: Array.isArray(report?.gap_report?.weak_concepts)
                ? report.gap_report.weak_concepts.map((item) => ({
                    concept: item.concept,
                    weaknessScore: Number(item.weakness_score || 0),
                    recommendation: item.recommendation || '',
                    misconceptions: Array.isArray(item.misconceptions) ? item.misconceptions : [],
                  }))
                : [],
              validationIssues: Array.isArray(report?.validation?.issues) ? report.validation.issues : [],
              planWeeks: Array.isArray(report?.plan?.weeks) ? report.plan.weeks.length : 0,
              raw: report,
            }
            addReportHistory(latestReport)
          }
        } catch {
          // Proceed with available local data when report endpoint is unavailable.
        }
      }

      let recommendedResources = Array.isArray(resources.recommended) ? resources.recommended : []
      if (!recommendedResources.length && user?.id && user?.isAuthenticated && String(user.id).startsWith('user_')) {
        try {
          const resourcePayload = await luminaApi.getResources(user.id)
          const mappedResources = mapResourcesToStore(resourcePayload)
          setResources(mappedResources)
          recommendedResources = mappedResources.recommended
        } catch {
          // Keep export functional with local fallback values.
        }
      }

      const planResourceMapForReport = collectPlanResources(latestReport)

      const strengthsFromQuiz = (Array.isArray(latestQuiz?.result?.concept_performance)
        ? latestQuiz.result.concept_performance
        : []
      )
        .slice()
        .sort((left, right) => Number(right.accuracy || 0) - Number(left.accuracy || 0))
        .slice(0, 4)
        .map((item) => {
          const resource = (planResourceMapForReport.get(normalizeText(item.concept)) || [])[0]
          return `${item.concept} (${toPercent(item.accuracy)}% accuracy, ${Number(item.attempts || 0)} attempts)${
            resource?.url ? ` | Resource: ${resource.url}` : ''
          }`
        })

      const strengthsFromMastery = (Array.isArray(progress.skillMastery) ? progress.skillMastery : [])
        .slice()
        .sort((left, right) => Number(right.value || 0) - Number(left.value || 0))
        .slice(0, 4)
        .map((item) => `${item.skill} (${Math.round(Number(item.value || 0))}% mastery)`)

      const strengths =
        strengthsFromQuiz.length > 0
          ? strengthsFromQuiz
          : strengthsFromMastery.length > 0
            ? strengthsFromMastery
            : ['Keep taking adaptive quizzes to generate strength insights.']

      const weakConcepts = Array.isArray(latestReport?.weakConcepts) ? latestReport.weakConcepts : []
      const weakDetailLookup = new Map(
        (Array.isArray(latestReport?.raw?.gap_report?.weak_concepts)
          ? latestReport.raw.gap_report.weak_concepts
          : []
        ).map((item) => [normalizeText(item.concept), item])
      )
      const weakFromHistory =
        weakConcepts.length > 0
          ? weakConcepts
              .slice()
              .sort((left, right) => Number(right.weaknessScore || 0) - Number(left.weaknessScore || 0))
              .slice(0, 5)
              .map((item) => {
                const conceptKey = normalizeText(item.concept)
                const detail = weakDetailLookup.get(conceptKey)
                const resource = (planResourceMapForReport.get(conceptKey) || [])[0]
                return `${item.concept} (weakness score ${Math.round(Number(item.weaknessScore || 0) * 100)}%)${
                  detail?.recommendation ? ` | ${detail.recommendation}` : ''
                }${resource?.url ? ` | Resource: ${resource.url}` : ''}`
              })
          : []

      const weakFromQuiz = (Array.isArray(latestQuiz?.result?.concept_performance)
        ? latestQuiz.result.concept_performance
        : []
      )
        .slice()
        .sort((left, right) => Number(left.accuracy || 0) - Number(right.accuracy || 0))
        .slice(0, 4)
        .map((item) => `${item.concept} (${toPercent(item.accuracy)}% accuracy)`)

      const weaknesses =
        weakFromHistory.length > 0
          ? weakFromHistory
          : weakFromQuiz.length > 0
            ? weakFromQuiz
            : ['No weak concept data available. Run a quiz check-in to populate this section.']

      const rawWeeks = Array.isArray(latestReport?.raw?.plan?.weeks) ? latestReport.raw.plan.weeks : []
      let planWeeks = rawWeeks.slice(0, 3).map((week, index) => {
        const parsedWeek = Number(String(week?.week ?? '').replace(/[^\d]/g, ''))
        const weekNumber = Number.isFinite(parsedWeek) && parsedWeek > 0 ? parsedWeek : index + 1
        const tasks = extractWeekTasks(week).slice(0, 4)
        return {
          week: weekNumber,
          goal: week?.goal || 'Focused improvement sprint',
          tasks,
        }
      })

      if (!planWeeks.length) {
        const fallbackResources = recommendedResources.slice(0, 3).map((resource) => resource.title)
        planWeeks = [1, 2, 3].map((weekNumber) => ({
          week: weekNumber,
          goal: `Week ${weekNumber} focus: ${weaknesses[Math.min(weekNumber - 1, weaknesses.length - 1)] || 'Skill reinforcement'}`,
          tasks: [
            `Complete 2 practice sessions on ${weaknesses[Math.min(weekNumber - 1, weaknesses.length - 1)] || 'priority concepts'}.`,
            fallbackResources[weekNumber - 1]
              ? `Study resource: ${fallbackResources[weekNumber - 1]}.`
              : 'Review one recommended learning resource.',
            'Take a short adaptive quiz check-in at the end of the week.',
          ],
        }))
      }

      const resourcesForPdf = recommendedResources.slice(0, 6).map((resource) => ({
        title: resource.title,
        meta: `${resource.type} | ${resource.duration} | ${resource.matchScore}% match`,
        url: resource.url || '',
      }))

      const reportSummaryCandidate = latestReport?.summary || latestReport?.raw?.gap_report?.summary || ''
      const summary = isPlaceholderSummary(reportSummaryCandidate)
        ? buildDynamicSummary({ entry: latestReport, progress, latestQuiz })
        : reportSummaryCandidate

      const highlightWeakness =
        Array.isArray(latestReport?.weakConcepts) && latestReport.weakConcepts.length
          ? latestReport.weakConcepts
              .slice()
              .sort((left, right) => Number(right.weaknessScore || 0) - Number(left.weaknessScore || 0))
              .slice(0, 2)
              .map((item) => `${item.concept} ${Math.round(Number(item.weaknessScore || 0) * 100)}%`)
              .join(' | ')
          : null

      const highlights = [
        `Plan completion: ${progress.planCompletion}%`,
        `Quiz average: ${progress.quizAverage}%`,
        `Weekly goals: ${progress.weeklyGoals.completed}/${progress.weeklyGoals.total}`,
        latestReport?.topic ? `Current focus: ${latestReport.topic}` : null,
        highlightWeakness ? `Top weak concepts: ${highlightWeakness}` : null,
      ].filter(Boolean)

      downloadLearningReportPdf({
        learnerName: user?.fullName || user?.name || 'Learner',
        generatedAt: new Date().toLocaleString(),
        summary,
        highlights,
        strengths,
        weaknesses,
        resources: resourcesForPdf,
        planWeeks,
      })

      showToast('PDF report exported successfully!')
    } catch (error) {
      showToast(error?.message || 'Unable to export PDF report right now.')
    }
  }

  const handleSendNote = () => {
    if (!note.trim()) return
    setNotes(prev => [...prev, { text: note, time: 'just now' }])
    setNote('')
    showToast('Note sent to mentor!')
  }

  const heatmap = progress.heatmap
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  const weeks = ['W1', 'W2', 'W3', 'W4']
  const heatColor = (val) => {
    if (!val) return 'rgba(255,255,255,0.04)'
    return `rgba(59,130,246,${0.2 + Math.min(1, val / 5) * 0.7})`
  }

  const statCards = [
    {
      label: 'Plan Completion', value: `${progress.planCompletion}%`,
      delta: `↑ ${progress.planCompletionDelta}% this week`, deltaPos: true,
      iconEl: (
        <div className="relative w-12 h-12">
          <svg className="rotate-[-90deg]" width="48" height="48" viewBox="0 0 36 36">
            <circle cx="18" cy="18" r="15" fill="none" stroke="rgba(59,130,246,0.15)" strokeWidth="3" />
            <circle cx="18" cy="18" r="15" fill="none" stroke="#3b82f6" strokeWidth="3"
              strokeDasharray={`${2 * Math.PI * 15 * progress.planCompletion / 100} 100`} strokeLinecap="round" />
          </svg>
          <div className="absolute inset-0 flex items-center justify-center">
            <i className="fa-solid fa-trophy text-blue-400 text-xs" />
          </div>
        </div>
      )
    },
    {
      label: 'Time Spent', value: `${progress.timeSpent.hours}h ${progress.timeSpent.minutes}m`,
      delta: `↑ ${progress.timeSpentDelta}`, deltaPos: true,
      iconEl: <div className="w-12 h-12 rounded-full flex items-center justify-center" style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)' }}><Clock size={18} className="text-blue-400" /></div>
    },
    {
      label: 'Quiz Average', value: `${progress.quizAverage}%`, delta: '— Steady', deltaPos: null,
      iconEl: <div className="w-12 h-12 rounded-full flex items-center justify-center" style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)' }}><BarChart2 size={18} className="text-blue-400" /></div>
    },
    {
      label: 'Weekly Goals', value: `${progress.weeklyGoals.completed}/${progress.weeklyGoals.total}`,
      delta: `${progress.weeklyGoals.total - progress.weeklyGoals.completed} goal remaining`, deltaPos: null,
      iconEl: <div className="w-12 h-12 rounded-full flex items-center justify-center" style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)' }}><Target size={18} className="text-blue-400" /></div>
    },
  ]

  const dateFilters = ['Last 7 Days', 'Last 30 Days', 'Last 90 Days']
  const persistedCoachingNotes = useMemo(() => {
    if (Array.isArray(progress.coachingNotes) && progress.coachingNotes.length) return progress.coachingNotes
    return [
      { name: 'Sarah Jenkins', time: 'yesterday', text: 'Great progress on the React hooks module! For the next week, focus more on the advanced routing concepts.' },
      { name: 'Sarah Jenkins', time: 'last week', text: "Make sure you're spending enough time on the practical exercises. Hands-on practice is where it clicks." },
    ]
  }, [progress.coachingNotes])

  const latestReport = useMemo(() => getMostRecentReport(reportHistory), [reportHistory])
  const planResourceMap = useMemo(() => collectPlanResources(latestReport), [latestReport])

  const latestSummary = useMemo(() => {
    const reportSummaryCandidate = latestReport?.summary || latestReport?.raw?.gap_report?.summary || ''
    return isPlaceholderSummary(reportSummaryCandidate)
      ? buildDynamicSummary({ entry: latestReport, progress, latestQuiz })
      : reportSummaryCandidate
  }, [latestReport, progress, latestQuiz])

  const strengthCards = useMemo(() => {
    const quizConcepts = (Array.isArray(latestQuiz?.result?.concept_performance)
      ? latestQuiz.result.concept_performance
      : []
    )
      .slice()
      .sort((left, right) => Number(right.accuracy || 0) - Number(left.accuracy || 0))
      .slice(0, 4)
      .map((item) => {
        const conceptKey = normalizeText(item.concept)
        const resource = (planResourceMap.get(conceptKey) || [])[0] || null
        return {
          concept: item.concept,
          score: toPercent(item.accuracy),
          subtitle: `${Number(item.attempts || 0)} attempts`,
          resource,
        }
      })

    if (quizConcepts.length) return quizConcepts

    return (Array.isArray(progress.skillMastery) ? progress.skillMastery : [])
      .slice()
      .sort((left, right) => Number(right.value || 0) - Number(left.value || 0))
      .slice(0, 4)
      .map((item) => ({
        concept: item.skill,
        score: Math.round(Number(item.value || 0)),
        subtitle: 'Mastery signal',
        resource: null,
      }))
  }, [latestQuiz, progress.skillMastery, planResourceMap])

  const weaknessCards = useMemo(() => {
    const weakConcepts = Array.isArray(latestReport?.weakConcepts) ? latestReport.weakConcepts : []
    const detailLookup = new Map(
      (Array.isArray(latestReport?.raw?.gap_report?.weak_concepts)
        ? latestReport.raw.gap_report.weak_concepts
        : []
      ).map((item) => [normalizeText(item.concept), item])
    )

    const fromReport = weakConcepts
      .slice()
      .sort((left, right) => Number(right.weaknessScore || 0) - Number(left.weaknessScore || 0))
      .slice(0, 5)
      .map((item) => {
        const conceptKey = normalizeText(item.concept)
        const detail = detailLookup.get(conceptKey)
        const resource = (planResourceMap.get(conceptKey) || [])[0] || null
        return {
          concept: item.concept,
          score: Math.round(Number(item.weaknessScore || 0) * 100),
          recommendation: detail?.recommendation || 'Reinforce with focused practice and reassessment.',
          resource,
        }
      })

    if (fromReport.length) return fromReport

    return (Array.isArray(latestQuiz?.result?.concept_performance)
      ? latestQuiz.result.concept_performance
      : []
    )
      .slice()
      .sort((left, right) => Number(left.accuracy || 0) - Number(right.accuracy || 0))
      .slice(0, 4)
      .map((item) => ({
        concept: item.concept,
        score: 100 - toPercent(item.accuracy),
        recommendation: `Improve ${item.concept} with two focused sessions this week.`,
        resource: null,
      }))
  }, [latestReport, latestQuiz, planResourceMap])

  const weeklyPathPreview = useMemo(() => {
    const fromPlan = buildWeeklyPathPreview(latestReport)
    if (fromPlan.length) return fromPlan

    const seedWeakness = weaknessCards[0]?.concept || 'priority concept'
    return [
      {
        week: 1,
        goal: `Foundation reset for ${seedWeakness}`,
        tasks: [`Study one core lesson for ${seedWeakness}.`, 'Complete one focused practice block.', 'Run one quick confidence check-in quiz.'],
      },
      {
        week: 2,
        goal: 'Applied practice and recall speed',
        tasks: ['Solve 12 mixed questions.', 'Review mistakes and write correction notes.', 'Time-box one revision sprint.'],
      },
      {
        week: 3,
        goal: 'Assessment and reinforcement',
        tasks: ['Take adaptive quiz check-in.', 'Compare weak-score changes.', 'Lock in next focus sprint.'],
      },
    ]
  }, [latestReport, weaknessCards])

  return (
    <div className="p-6 flex flex-col gap-6">
      {toast && <Toast msg={toast} onClose={() => setToast(null)} />}

      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white">Progress Tracking</h1>
          <p className="text-sm mt-1" style={{ color: '#64748b' }}>Monitor your learning journey and bootcamp performance.</p>
        </div>
        <div className="flex items-center gap-3">
          {/* Date range toggle */}
          <div className="flex p-1 rounded-lg" style={{ background: 'rgba(15,23,42,0.6)', border: '1px solid #334155' }}>
            {dateFilters.map(f => (
              <button key={f} onClick={() => setDateRange(f)}
                className="px-3 py-1.5 rounded-md text-xs font-medium transition-all flex items-center gap-1.5"
                style={{
                  background: dateRange === f ? '#1e293b' : 'transparent',
                  color: dateRange === f ? '#60a5fa' : '#94a3b8',
                  border: dateRange === f ? '1px solid #334155' : '1px solid transparent',
                }}>
                <Calendar size={11} /> {f}
              </button>
            ))}
          </div>
          <button onClick={handleExport}
            className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium text-white transition-all hover:opacity-90 primary-btn">
            <Download size={14} /> Export PDF Report
          </button>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {statCards.map((card, i) => (
          <div key={i} className="glass-card rounded-[16px] p-5 flex items-center justify-between" style={{ background: 'rgba(30,41,59,0.4)', border: '1px solid rgba(255,255,255,0.08)' }}>
            <div>
              <p className="text-xs mb-1" style={{ color: '#94a3b8' }}>{card.label}</p>
              <h3 className="text-2xl font-bold text-white mb-1">{card.value}</h3>
              <p className={`text-xs font-medium flex items-center gap-1 ${card.deltaPos === true ? 'text-emerald-400' : card.deltaPos === false ? 'text-red-400' : 'text-slate-500'}`}>
                {card.deltaPos === true && <TrendingUp size={11} />}{card.delta}
              </p>
            </div>
            {card.iconEl}
          </div>
        ))}
      </div>

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Line Chart */}
        <div className="lg:col-span-2 glass-panel rounded-[16px] border border-slate-700/50 p-5">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-semibold text-white">Quiz Performance Trend</h2>
            <select value={moduleFilter} onChange={e => setModuleFilter(e.target.value)}
              className="text-xs rounded-lg px-3 py-1.5 outline-none cursor-pointer"
              style={{ background: 'rgba(15,23,42,0.6)', border: '1px solid #334155', color: '#cbd5e1' }}>
              {['All Modules', 'Module 1', 'Module 2', 'Module 3'].map(o => (
                <option key={o} style={{ background: '#0f172a' }}>{o}</option>
              ))}
            </select>
          </div>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={progress.weeklyData} margin={{ top: 5, right: 5, bottom: 5, left: -20 }}>
                <CartesianGrid stroke="rgba(255,255,255,0.04)" vertical={false} />
                <XAxis dataKey="week" tick={{ fill: '#475569', fontSize: 11 }} axisLine={false} tickLine={false} />
                <YAxis domain={[0, 100]} tick={{ fill: '#475569', fontSize: 11 }} axisLine={false} tickLine={false} />
                <Tooltip content={<ProgressLineTooltip />} />
                <Line type="monotone" dataKey="score" stroke="#3b82f6" strokeWidth={2}
                  dot={{ fill: '#3b82f6', r: 4, strokeWidth: 0 }} activeDot={{ r: 6, fill: '#60a5fa' }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Radar Chart */}
        <div className="glass-panel rounded-[16px] border border-slate-700/50 p-5">
          <h2 className="text-sm font-semibold text-white mb-4">Skill Mastery</h2>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart data={progress.skillMastery} outerRadius={90}>
                <PolarGrid stroke="rgba(255,255,255,0.07)" />
                <PolarAngleAxis dataKey="skill" tick={{ fill: '#64748b', fontSize: 10 }} />
                <PolarRadiusAxis domain={[0, 100]} tick={false} axisLine={false} />
                <Radar name="Mastery" dataKey="value" stroke="#3b82f6" fill="#3b82f6" fillOpacity={0.15} strokeWidth={1.5} />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Heatmap + Coaching */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Heatmap */}
        <div className="lg:col-span-2 glass-panel rounded-[16px] border border-slate-700/50 p-5">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-semibold text-white">Time Distribution Heatmap</h2>
            <div className="flex items-center gap-2 text-xs" style={{ color: '#64748b' }}>
              <span>Less</span>
              {[0.1, 0.3, 0.6, 0.9].map((o, i) => (
                <div key={i} className="w-3.5 h-3.5 rounded-sm" style={{ background: `rgba(59,130,246,${o})` }} />
              ))}
              <span>More</span>
            </div>
          </div>
          <div className="flex gap-2 mb-1 pl-7">
            {days.map(d => <div key={d} className="flex-1 text-center text-[10px]" style={{ color: '#475569' }}>{d}</div>)}
          </div>
          <div className="flex flex-col gap-1.5">
            {heatmap.map((week, wi) => (
              <div key={wi} className="flex items-center gap-2">
                <span className="text-[10px] w-5 shrink-0" style={{ color: '#475569' }}>{weeks[wi]}</span>
                <div className="flex gap-2 flex-1">
                  {week.map((val, di) => (
                    <div key={di} title={`${days[di]}: ${val}h`}
                      className="flex-1 h-6 rounded-sm transition-all cursor-default hover:opacity-80"
                      style={{ background: heatColor(val) }} />
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Coaching Notes */}
        <div className="glass-panel rounded-[16px] border border-slate-700/50 p-5 flex flex-col">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-semibold text-white">Coaching Notes</h2>
            <span className="text-xs px-2 py-1 rounded" style={{ background: 'rgba(255,255,255,0.06)', color: '#94a3b8' }}>Bootcamp Mentor</span>
          </div>
          <div className="flex-1 flex flex-col gap-4 overflow-y-auto mb-4 max-h-[200px] pr-1">
            {[...persistedCoachingNotes, ...notes.map(n => ({ name: 'You', time: n.time, text: n.text }))].map((note, i) => (
              <div key={i} className="flex gap-3">
                <Avatar name={note.name} size={28} className="shrink-0 mt-0.5" />
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs font-semibold text-white">{note.name}</span>
                    <span className="text-[10px]" style={{ color: '#64748b' }}>{note.time}</span>
                  </div>
                  <p className="text-xs leading-relaxed" style={{ color: '#94a3b8' }}>{note.text}</p>
                </div>
              </div>
            ))}
          </div>
          <div className="relative">
            <textarea
              value={note}
              onChange={e => setNote(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && !e.shiftKey && (e.preventDefault(), handleSendNote())}
              placeholder="Add a note or reply to mentor… (Enter to send)"
              rows={3}
              className="w-full p-3 pr-12 rounded-lg text-sm resize-none outline-none"
              style={{ background: 'rgba(15,23,42,0.6)', border: '1px solid #334155', color: '#e2e8f0' }} />
            <button onClick={handleSendNote}
              className="absolute bottom-2 right-2 w-8 h-8 rounded flex items-center justify-center text-white transition-colors hover:bg-blue-500"
              style={{ background: '#2563eb' }}>
              <i className="fa-solid fa-paper-plane text-xs" />
            </button>
          </div>
        </div>
      </div>

      <div className="glass-panel rounded-[16px] border border-slate-700/50 p-5">
        <div className="flex items-center justify-between mb-4 gap-3">
          <div>
            <h2 className="text-sm font-semibold text-white">Actionable Report</h2>
            <p className="text-xs mt-1" style={{ color: '#94a3b8' }}>Strengths, weaknesses, and weekly path in one view.</p>
          </div>
          <Link to="/learning-path" className="text-xs font-medium text-blue-400 hover:text-blue-300">
            Open Visual Learning Path
          </Link>
        </div>

        <div className="rounded-lg p-4 mb-4" style={{ background: 'rgba(15,23,42,0.55)', border: '1px solid rgba(51,65,85,0.5)' }}>
          <p className="text-xs leading-relaxed whitespace-pre-line" style={{ color: '#cbd5e1' }}>
            {latestSummary || 'No report summary available yet. Complete an adaptive quiz and generate a plan.'}
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          <div className="rounded-lg p-4" style={{ background: 'rgba(16,185,129,0.08)', border: '1px solid rgba(16,185,129,0.25)' }}>
            <p className="text-xs font-semibold text-emerald-300 mb-3 uppercase tracking-wider">Strengths</p>
            <div className="space-y-2">
              {strengthCards.length === 0 && (
                <p className="text-xs" style={{ color: '#cbd5e1' }}>No strength data yet.</p>
              )}
              {strengthCards.map((item) => (
                <div key={item.concept} className="rounded-md p-2" style={{ background: 'rgba(15,23,42,0.5)', border: '1px solid rgba(148,163,184,0.2)' }}>
                  <p className="text-xs text-white font-medium">{item.concept}</p>
                  <p className="text-[11px]" style={{ color: '#6ee7b7' }}>{item.score}%</p>
                  <p className="text-[10px]" style={{ color: '#94a3b8' }}>{item.subtitle}</p>
                  {item.resource?.url && (
                    <a href={item.resource.url} target="_blank" rel="noreferrer" className="text-[10px] text-blue-300 hover:text-blue-200">
                      {item.resource.title || 'Open resource'}
                    </a>
                  )}
                </div>
              ))}
            </div>
          </div>

          <div className="rounded-lg p-4" style={{ background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.25)' }}>
            <p className="text-xs font-semibold text-amber-300 mb-3 uppercase tracking-wider">Weaknesses</p>
            <div className="space-y-2">
              {weaknessCards.length === 0 && (
                <p className="text-xs" style={{ color: '#cbd5e1' }}>No weakness data yet.</p>
              )}
              {weaknessCards.map((item) => (
                <div key={item.concept} className="rounded-md p-2" style={{ background: 'rgba(15,23,42,0.5)', border: '1px solid rgba(148,163,184,0.2)' }}>
                  <p className="text-xs text-white font-medium">{item.concept}</p>
                  <p className="text-[11px]" style={{ color: '#fcd34d' }}>{item.score}% weakness</p>
                  <p className="text-[10px] leading-relaxed" style={{ color: '#cbd5e1' }}>{item.recommendation}</p>
                  {item.resource?.url && (
                    <a href={item.resource.url} target="_blank" rel="noreferrer" className="text-[10px] text-blue-300 hover:text-blue-200">
                      {item.resource.title || 'Open recovery resource'}
                    </a>
                  )}
                </div>
              ))}
            </div>
          </div>

          <div className="rounded-lg p-4" style={{ background: 'rgba(59,130,246,0.08)', border: '1px solid rgba(59,130,246,0.25)' }}>
            <p className="text-xs font-semibold text-blue-300 mb-3 uppercase tracking-wider">Weekly Learning Path</p>
            <div className="space-y-2">
              {weeklyPathPreview.map((week) => (
                <div key={week.week} className="rounded-md p-2" style={{ background: 'rgba(15,23,42,0.5)', border: '1px solid rgba(148,163,184,0.2)' }}>
                  <p className="text-xs font-medium text-white">Week {week.week}</p>
                  <p className="text-[10px] mb-1" style={{ color: '#93c5fd' }}>{week.goal}</p>
                  {(Array.isArray(week.tasks) ? week.tasks : []).slice(0, 2).map((task, idx) => (
                    <p key={`${week.week}_${idx}`} className="text-[10px]" style={{ color: '#cbd5e1' }}>
                      {idx + 1}. {task}
                    </p>
                  ))}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="glass-panel rounded-[16px] border border-slate-700/50 p-5">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-sm font-semibold text-white">Progress Report History</h2>
          <span className="text-xs" style={{ color: '#94a3b8' }}>{reportHistory.length} reports</span>
        </div>
        {reportHistory.length === 0 ? (
          <p className="text-sm" style={{ color: '#64748b' }}>No reports yet. Complete an adaptive quiz check-in to generate your first progressive report.</p>
        ) : (
          <div className="space-y-3">
            {reportHistory.slice(0, 8).map((entry) => {
              const reportSummaryCandidate = entry?.summary || entry?.raw?.gap_report?.summary || ''
              const displaySummary = isPlaceholderSummary(reportSummaryCandidate)
                ? buildDynamicSummary({ entry, progress, latestQuiz })
                : reportSummaryCandidate

              const weakConcepts = Array.isArray(entry?.weakConcepts) ? entry.weakConcepts : []
              const weakChips = weakConcepts
                .slice()
                .sort((left, right) => Number(right.weaknessScore || 0) - Number(left.weaknessScore || 0))
                .slice(0, 3)

              return (
                <div key={entry.id} className="rounded-lg p-4" style={{ background: 'rgba(15,23,42,0.6)', border: '1px solid rgba(51,65,85,0.5)' }}>
                  <div className="flex items-center justify-between mb-2">
                    <p className="text-sm font-medium text-white">{entry.topic}</p>
                    <p className="text-xs" style={{ color: '#94a3b8' }}>{new Date(entry.createdAt).toLocaleString()}</p>
                  </div>
                  <p className="text-xs mb-3 leading-relaxed whitespace-pre-line" style={{ color: '#cbd5e1' }}>
                    {displaySummary || 'No summary available.'}
                  </p>
                  <div className="flex flex-wrap gap-2 text-[11px] mb-2">
                    {typeof entry.accuracy === 'number' && (
                      <span className="px-2 py-1 rounded" style={{ background: 'rgba(59,130,246,0.15)', color: '#93c5fd' }}>
                        Accuracy: {entry.accuracy}%
                      </span>
                    )}
                    {entry.planWeeks ? (
                      <span className="px-2 py-1 rounded" style={{ background: 'rgba(16,185,129,0.12)', color: '#6ee7b7' }}>
                        Plan Weeks: {entry.planWeeks}
                      </span>
                    ) : null}
                    <span className="px-2 py-1 rounded" style={{ background: 'rgba(148,163,184,0.12)', color: '#cbd5e1' }}>
                      Source: {entry.source || 'unknown'}
                    </span>
                  </div>
                  {weakChips.length > 0 && (
                    <div className="flex flex-wrap gap-2 text-[11px]">
                      {weakChips.map((item) => (
                        <span key={`${entry.id}_${item.concept}`} className="px-2 py-1 rounded" style={{ background: 'rgba(245,158,11,0.14)', color: '#fcd34d' }}>
                          {item.concept}: {Math.round(Number(item.weaknessScore || 0) * 100)}%
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        )}
      </div>
    </div>
  )
}

export default ProgressPage
